apiVersion: v1
kind: Service
metadata:
  name: mon-app-svc
spec:
  type: NodePort
  selector:
    app: mon-app
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080 # optionnel : fixe le port pour l'accès via NodePort
